apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: api-carupi
        image: 839678231069.dkr.ecr.sa-east-1.amazonaws.com/carupi:latest
        ports:
        - name: http
          containerPort: 3333
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux